function [y, delta] = polyval(p,x,S,mu)
// Evaluate a polynomial at specified points.
//
// Syntax
//   y = polyval(p, x)
//   [y, delta] = polyval(p, x, S)
//   [y, delta] = polyval(p, x, S, mu)
//
// Parameters
// p: Coefficients of the polynomial (vector). The coefficients are in descending powers of the polynomial.
// x: Points at which the polynomial is evaluated (vector or matrix).
// S: (optional) Structure generated by `polyfit` for error estimation.
// mu: (optional) Centering and scaling parameters [mean, std] for x.
//
// Description
// The `polyval` function evaluates a polynomial at specified points using its coefficients. 
// It supports error estimation when used with the structure `S` from `polyfit`. 
// If centering and scaling parameters `mu` are provided, the evaluation is performed on scaled values of `x`.
//
// Notes
// - The function uses Horner's method for efficient polynomial evaluation.
// - If `S` is provided, `delta` estimates the standard deviation of the error in predicting future observations.
//
// Examples
// // Evaluate a polynomial at specific points:
//    p = [3, 2, 1];
//    y = polyval(p, [5, 7, 9])
// 
//
// // Evaluate with error estimation:
//    p = [3, 2, 1];
//    S = polyfit([1, 2, 3], [4, 5, 6], 2);
//    [y, delta] = polyval(p, [5, 7, 9], S)
//
// // Evaluate with centering and scaling:
//    p = [3, 2, 1];
//    mu = [mean([1, 2, 3]), std([1, 2, 3])];
//    y = polyval(p, [5, 7, 9], [], mu)
//



if ~(isvector(p) | isempty(p))  // Check input is a vector
    error('polyval:InvalidP');
end

nc = length(p);
if isscalar(x) & (argn(2) < 3) & nc>0 & (abs(x)<%inf) & and(abs(p(:))<%inf)
    // Make it scream for scalar x.  Polynomial evaluation can be
    // implemented as a recursive digital filter.
    y = filter(1,[1 -real(x)],p);
    y = y(nc);
    return
end

siz_x = size(x);
if argn(2) == 4
   x = (x - mu(1))/mu(2);
end

// Use Horner's method for general case where X is an array.
y = zeros(size(x,1),size(x,2));
if nc>0, y(:) = p(1); end
for i=2:nc
    y = x .* y + p(i);
end

if argn(1) > 1
    if argn(2) < 3 | isempty(S)
        error('polyval:Requires S');
    end

    // Extract parameters from S
    if isstruct(S),  // Use output structure from polyfit.
      R = S.R;
      df = S.df;
      normr = S.normr;
    else             // Use output matrix from previous versions of polyfit.
      [ms,ns] = size(S);
      if (ms ~= ns+2) | (nc ~= ns)
          error('polyval:SizeS');
      end
      R = S(1:nc,1:nc);
      df = S(nc+1,1);
      normr = S(nc+2,1);
    end

    // Construct Vandermonde matrix for the new X.
    x = x(:);
    V(:,nc) = ones(length(x),1,class(x));
    for j = nc-1:-1:1
        V(:,j) = x.*V(:,j+1);
    end

    // S is a structure containing three elements: the triangular factor of
    // the Vandermonde matrix for the original X, the degrees of freedom,
    // and the norm of the residuals.
    E = V/R;
    e = sqrt(1+sum(E.*E,2));
    if df == 0
        warning('polyval:ZeroDOF');
        delta = %inf(size(e));
    else
        delta = normr/sqrt(df)*e;
    end
    delta = matrix(delta,siz_x);
end
endfunction
